{
 "title": "SWE Dashboard - Metrics",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "MRs/PRs Throughput ",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "merge_request_throughput{}", "legendFormat": "{{repository}}" }
   ]
  },
  {
   "title": "MRs/PRs Rates",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "merge_request_rate{}", "legendFormat": "{{repository}}" }
   ]
  },
  {
   "title": "MRs/PRs Success Rate",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort(merge_request_success_rate{})",
     "legendFormat": "{{repository}}"
    }
   ]
  },
  {
   "title": "MRs/PRs Success Rate Trend",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
   "targets": [
    { "expr": "merge_request_success_rate{}", "legendFormat": "{{repository}}" }
   ]
  },
  {
   "title": "Friday MRs/PRs",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by (repository) (friday_merge_request{}))",
     "legendFormat": "{{repository}}"
    }
   ]
  },
  {
   "title": "Unreviewed MRs/PRs",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by (repository) (unreviewed_merge_request{}))",
     "legendFormat": "{{repository}}"
    }
   ]
  },
  {
   "title": "MRs/PRs Comments",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(comments_leaderboard{})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "MRs/PRs Participants",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(participants_leaderboard{})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Self-Merging Users",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sort_desc(self_merging{})", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Cycle Time",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc( (sum by (repository) (cycle_time{})[1h] / count by (repository) (cycle_time{})[1h]) )",
     "legendFormat": "{{repository}}"
    }
   ]
  },
  {
   "title": "Repository Defect Rate",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sort_desc(defect_rate{})", "legendFormat": "{{repository}}" }
   ]
  },
  {
   "title": "Repository Defect Rate Trend",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "defect_rate{}", "legendFormat": "{{repository}}" }
   ]
  },
  {
   "title": "User Defect Rate",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by (username, name) (defect_rate_user))",
     "legendFormat": "{{username}} ({{name}})"
    }
   ]
  },
  {
   "title": "User Defect Rate Trend",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (username, name) (defect_rate_user)",
     "legendFormat": "{{username}} ({{name}})"
    }
   ]
  },
  {
   "title": "Time To Open",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc( (sum by (repository) (time_to_open{})[1h] / count by (repository) (time_to_open{})[1h]) )",
     "legendFormat": "{{repository}}"
    }
   ]
  },
  {
   "title": "Time To Open Trend",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (repository) (time_to_open{})[1h] / count by (repository) (time_to_open{})[1h]",
     "legendFormat": "{{repository}}"
    }
   ]
  },
  {
   "title": "Time to Review",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc( (sum by (repository) (time_to_review{})[1h] / count by (repository) (time_to_review{})[1h]) )",
     "legendFormat": "{{repository}}"
    }
   ]
  },
  {
   "title": "Time to Review Trend",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(sum by (repository) (time_to_review{})[1h] / count by (repository) (time_to_review{})[1h]) ",
     "legendFormat": "{{repository}}"
    }
   ]
  },
  {
   "title": "Time to Approve",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc( (sum by (repository) (time_to_approve{})[1h] / count by (repository) (time_to_approve{})[1h]) )",
     "legendFormat": "{{repository}}"
    }
   ]
  },
  {
   "title": "Time to Approve Trend",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(sum by (repository) (time_to_approve{})[1h] / count by (repository) (time_to_approve{})[1h]) ",
     "legendFormat": "{{repository}}"
    }
   ]
  },
  {
   "title": "Time to Merge",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc( (sum by (repository) (time_to_merge{})[1h] / count by (repository) (time_to_merge{})[1h]) )",
     "legendFormat": "{{repository}}"
    }
   ]
  },
  {
   "title": "Time to Merge Trend",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (repository) (time_to_merge{})[1h] / count by (repository) (time_to_merge{})[1h]",
     "legendFormat": "{{repository}}"
    }
   ]
  }
 ]
}