{
 "title": "SWE Dashboard - Repository",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "repository", "label": "Repository", "query": { "query": "commit_additions" } },
   {
    "name": "mergerequest",
    "label": "MR/PR",
    "query": {
     "query": "time_to_open{repository=\"$repository\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Additions/Deletions Line of Code (last 30 days)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (commit_additions{repository=\"$repository\"})",
     "legendFormat": "Additions"
    },
    {
     "expr": "sum (commit_deletions{repository=\"$repository\"})",
     "legendFormat": "Deletions"
    }
   ]
  },
  {
   "title": "Review Speed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (repository) (time_to_review{repository=\"$repository\"}) / count by (repository) (time_to_review{repository=\"$repository\"})",
     "legendFormat": "Review Speed"
    }
   ]
  },
  {
   "title": "Open Speed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (repository) (time_to_open{repository=\"$repository\"}) / count by (repository) (time_to_open{repository=\"$repository\"})",
     "legendFormat": "Open Speed"
    }
   ]
  },
  {
   "title": "Merge Speed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (repository) (time_to_merge{repository=\"$repository\"}) / count by (repository) (time_to_merge{repository=\"$repository\"})",
     "legendFormat": "Merge Speed"
    }
   ]
  },
  {
   "title": "Cycle Time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (repository) (cycle_time{repository=\"$repository\"})[10m] / count by (repository) (cycle_time{repository=\"$repository\"})[10m])",
     "legendFormat": "{{repository}}"
    }
   ]
  },
  {
   "title": "Defect Rate",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 5, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "defect_rate{repository=\"$repository\"}"
    }
   ]
  },
  {
   "title": "MRs/PRs Success Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "merge_request_success_rate{repository=\"$repository\"}"
    }
   ]
  },
  {
   "title": "Approved Speed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 11, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (repository) (time_to_approve{repository=\"$repository\"}) / count by (repository) (time_to_approve{repository=\"$repository\"})",
     "legendFormat": "Approved Speed"
    }
   ]
  },
  {
   "title": "Unreviewed MRs/PRs",
   "type": "stat",
   "description": "### Unreviewed MRs/PRs\n\nThe percentage of pull requests that were merged without review.",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "unreviewed_merge_request{repository=\"$repository\"}",
     "legendFormat": "{{repository}}"
    }
   ]
  },
  {
   "title": "MRs/PRs Throughput ",
   "type": "timeseries",
   "description": "### MRs/PRs Throughput \n\nA count of how many pull requests are merged over a period of time.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "merge_request_throughput{repository=\"$repository\"}",
     "legendFormat": "{{repository}}"
    }
   ]
  },
  {
   "title": "MRs/PRs Rates",
   "type": "timeseries",
   "description": "### MRs/PRs Rates\n\nThis is the ratio of product MRs authored by team members in Development Department to the number of team members in the Development Department. ",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "merge_request_rate{repository=\"$repository\"}",
     "legendFormat": "{{repository}}"
    }
   ]
  },
  {
   "title": "Active Contributors for $repository (last 30 days)",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by (author,email) (active_contributors{repository=\"$repository\"}))",
     "legendFormat": "{{author}} ({{email}})"
    }
   ]
  },
  {
   "title": "Additions/Deletions Line of Code",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (commit_additions{repository=\"$repository\"})",
     "legendFormat": "Additions"
    },
    {
     "expr": "sum (-1 * commit_deletions{repository=\"$repository\"})",
     "legendFormat": "Deletions"
    }
   ]
  },
  {
   "title": "Additions Line of Code by User",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (author, email) (commit_additions{repository=\"$repository\"})",
     "legendFormat": "{{author}} ({{email}})"
    }
   ]
  },
  {
   "title": "Deletions Line of Code by User",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (author, email) (commit_deletions{repository=\"$repository\"})",
     "legendFormat": "{{author}} ({{email}})"
    }
   ]
  },
  {
   "title": "MRs/PRs Size Counts for $repository",
   "type": "bargauge",
   "description": "### MRs/PRs Size\n\nThe number of lines of code that were added, changed or removed.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(merge_request_size{repository=\"$repository\"} <= 9)",
     "legendFormat": "XS"
    },
    {
     "expr": "count(merge_request_size{repository=\"$repository\"} > 10 and merge_request_size{repository=\"$repository\"} < 29)",
     "legendFormat": "S"
    },
    {
     "expr": "count(merge_request_size{repository=\"$repository\"} > 30 and merge_request_size{repository=\"$repository\"} < 99)  ",
     "legendFormat": "M"
    },
    {
     "expr": "count(merge_request_size{repository=\"$repository\"} > 100 and merge_request_size{repository=\"$repository\"} < 499)  ",
     "legendFormat": "L"
    },
    {
     "expr": "count(merge_request_size{repository=\"$repository\"} > 500 and merge_request_size{repository=\"$repository\"} < 999)  ",
     "legendFormat": "XL"
    },
    {
     "expr": "count(merge_request_size{repository=\"$repository\"} > 1000 )  ",
     "legendFormat": "XXL"
    }
   ]
  },
  {
   "title": "MRs/PRs Size Trend for $repository",
   "type": "timeseries",
   "description": "### MRs/PRs Size\n\nThe number of lines of code that were added, changed or removed.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "count(merge_request_size{repository=\"$repository\"} <= 9)",
     "legendFormat": "XS"
    },
    {
     "expr": "count(merge_request_size{repository=\"$repository\"} > 10 and merge_request_size{repository=\"$repository\"} < 29)",
     "legendFormat": "S"
    },
    {
     "expr": "count(merge_request_size{repository=\"$repository\"} > 30 and merge_request_size{repository=\"$repository\"} < 99)  ",
     "legendFormat": "M"
    },
    {
     "expr": "count(merge_request_size{repository=\"$repository\"} > 100 and merge_request_size{repository=\"$repository\"} < 499)  ",
     "legendFormat": "L"
    },
    {
     "expr": "count(merge_request_size{repository=\"$repository\"} > 500 and merge_request_size{repository=\"$repository\"} < 999)  ",
     "legendFormat": "XL"
    },
    {
     "expr": "count(merge_request_size{repository=\"$repository\"} > 1000 )  ",
     "legendFormat": "XXL"
    }
   ]
  },
  {
   "title": "Unreviewed MRs/PRs Trend for $repository",
   "type": "timeseries",
   "description": "### Unreviewed MRs/PRs\n\nThe percentage of pull requests that were merged without review.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "unreviewed_merge_request{repository=\"$repository\"}",
     "legendFormat": "{{repository}}"
    }
   ]
  },
  {
   "title": "Defect Rate Average for $repository (last 30 days)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sort_desc(avg by (repository) (defect_rate_user{repository=\"$repository\"}))",
     "legendFormat": "Rate"
    }
   ]
  },
  {
   "title": "Cycle Time by MRs/PRs for $repository (last 30 days)",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(cycle_time{repository=\"$repository\"})",
     "legendFormat": "{{title}}"
    }
   ]
  },
  {
   "title": "MRs/PRs Times for $mergerequest",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time_to_open{repository=\"$repository\",title=\"$mergerequest\"}",
     "legendFormat": "Time to Open"
    },
    {
     "expr": "time_to_review{repository=\"headball2\",title=\"$mergerequest\"}",
     "legendFormat": "Time to Review"
    },
    {
     "expr": "time_to_approve{repository=\"$repository\",title=\"$mergerequest\"}",
     "legendFormat": "Time to Approve"
    },
    {
     "expr": "time_to_merge{repository=\"$repository\",title=\"$mergerequest\"}",
     "legendFormat": "Time to Merge"
    }
   ]
  },
  {
   "title": "User Defect Rate for $repository (last 30 days)",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by (username, name) (defect_rate_user{repository=\"$repository\"}))",
     "legendFormat": "{{name}} ({{username}})"
    }
   ]
  },
  {
   "title": "User Defect Rate for $repository (last 30 days)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sort_desc(sum by (username, name) (defect_rate_user{repository=\"$repository\"}))",
     "legendFormat": "{{name}} ({{username}})"
    }
   ]
  },
  {
   "title": "MRs/PRs Speeds for $repository (last 30 days)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (repository) (time_to_open{repository=\"$repository\"}) / count by (repository) (time_to_open{repository=\"$repository\"})",
     "legendFormat": "Open Speed"
    },
    {
     "expr": "sum by (repository) (time_to_review{repository=\"$repository\"}) / count by (repository) (time_to_review{repository=\"$repository\"})",
     "legendFormat": "Review Speed"
    },
    {
     "expr": "sum by (repository) (time_to_approve{repository=\"$repository\"}) / count by (repository) (time_to_approve{repository=\"$repository\"})",
     "legendFormat": "Approved Speed"
    },
    {
     "expr": "sum by (repository) (time_to_merge{repository=\"$repository\"}) / count by (repository) (time_to_merge{repository=\"$repository\"})",
     "legendFormat": "Merge Speed"
    }
   ]
  },
  {
   "title": "MRs/PRs Success Rate for $repository (last 30 days)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "merge_request_success_rate{repository=\"$repository\"}",
     "legendFormat": "{{repository}}"
    }
   ]
  },
  {
   "title": "Long Running MRs/PRs for $repository (last 90 days)",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(long_running_merge_request{repository=\"$repository\"})",
     "legendFormat": "{{title}}"
    }
   ]
  },
  {
   "title": "MRs/PRs Sizes for $repository",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 125 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum(merge_request_size{repository=\"$repository\"}) by (title))",
     "legendFormat": "{{repository}}"
    }
   ]
  }
 ]
}