version: "3.5"
services:
  victoriametrics:
    container_name: swed-victoriametrics
    image: victoriametrics/victoria-metrics
    ports:
      - 8428:8428
    command:
      - "--storageDataPath=/storage"
      - "--httpListenAddr=:8428"
      - "-retentionPeriod=6" #six months
    networks:
      - swed_net
    restart: always
  grafana:
    container_name: swed-grafana
    image: grafana/grafana
    depends_on:
      - "victoriametrics"
    ports:
      - 3000:3000
    volumes:
      - ./dashboards/dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./datasources/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
      - ./../grafana/swe-dashboard-metrics.json:/var/lib/grafana/dashboards/swe-dashboard-metrics.json
      - ./../grafana/swe-dashboard-repository.json:/var/lib/grafana/dashboards/swe-dashboard-repository.json
    networks:
      - swed_net
    restart: always
networks:
  swed_net: null
