version: '3.5'
services:
  victoriametrics:
    container_name: victoriametrics
    image: victoriametrics/victoria-metrics
    ports:
      - 8428:8428
      - 8089:8089
      - 8089:8089/udp
      - 2003:2003
      - 2003:2003/udp
      - 4242:4242
    volumes:
      - vmdata:/storage
    command:
      - '--storageDataPath=/storage'
      - '--graphiteListenAddr=:2003'
      - '--opentsdbListenAddr=:4242'
      - '--httpListenAddr=:8428'
      - '--influxListenAddr=:8089'
    networks:
      - vm_net
    restart: always
  grafana:
    container_name: grafana
    image: grafana/grafana
    depends_on:
      - "victoriametrics"
    ports:
      - 3000:3000
    volumes:
      - grafanadata:/var/lib/grafana
      - ./tmp/:/etc/grafana/provisioning
      - ./tmp/dashboards:/etc/grafana/provisioning/dashboards
      - ./tmp/datasources:/etc/grafana/provisioning/datasources
      - ./tmp/plugins:/etc/grafana/provisioning/plugins
      - ./tmp/notifiers:/etc/grafana/provisioning/notifiers
    networks:
      - vm_net
    restart: always
volumes:
  vmdata: {}
  grafanadata: {}
networks:
  vm_net: null
