version: "3.5"
services:
  victoriametrics:
    container_name: swed-victoriametrics
    image: victoriametrics/victoria-metrics
    ports:
      - 8428:8428
    volumes:
      - swed_victoriametrics:/storage
    command:
      - "--storageDataPath=/storage"
      - "--httpListenAddr=:8428"
      - "-retentionPeriod=1y"
      - "-search.disableAutoCacheReset"
    networks:
      - swed_net
    restart: always
  grafana:
    container_name: swed-grafana
    image: grafana/grafana
    depends_on:
      - "victoriametrics"
    ports:
      - 3000:3000
    volumes:
      - swed_grafana:/var/lib/grafana
    networks:
      - swed_net
    restart: always
volumes:
  swed_victoriametrics: {}
  swed_grafana: {}
networks:
  swed_net: null
